# Generated by Django 5.0.6 on 2024-11-20 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shery_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
    ]
