# Generated by Django 5.0.6 on 2024-11-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shery_app', '0003_customuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(null=True,blank=True,default=None, upload_to='media/profile_pictures'),
            preserve_default=False,
        ),
    ]
