# Generated by Django 5.0.6 on 2024-11-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shery_app', '0005_alter_customuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.FileField(blank=True,default=None, null=True, upload_to='media/profile_pictures'),
        ),
    ]
