# Generated by Django 5.0.6 on 2024-11-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shery_app', '0008_alter_customuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Description',
            field=models.CharField(max_length=400),
        ),
    ]
