# Generated by Django 5.0.6 on 2024-11-27 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shery_app', '0009_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollement',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shery_app.course'),
        ),
    ]
